### ISSUE TITLE
Sparse index error

### ISSUE THREAD

**Issue by xiyanghu** [castorini/mr.tydi#7]
When I tried to use the provided script to get the sparse index on the dataset, error raises as below:

But the docs.jsonl file only have two fields: "id" and"contents". 

I also checked the jsonl files in `anserini/src/test/resources/sample_docs/mrtydi-1.1/`, those files have three fields: "docid", "title", "text".

`java.lang.RuntimeException: Document does not have the required "docid" field!
 at io.anserini.collection.MrTyDiCollection$Document.id(MrTyDiCollection.java:126) ~[anserini-0.14.4-SNAPSHOT.jar:?]
 at io.anserini.index.generator.DefaultLuceneDocumentGenerator.createDocument(DefaultLuceneDocumentGenerator.java:57) ~[anserini-0.14.4-SNAPSHOT.jar:?]
 at io.anserini.index.IndexCollection$LocalIndexerThread.run(IndexCollection.java:202) [anserini-0.14.4-SNAPSHOT.jar:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
 at java.lang.Thread.run(Thread.java:829) [?:?]
2022-07-04 03:01:06,142 ERROR [pool-2-thread-1] collection.MrTyDiCollection$Segment (MrTyDiCollection.java:92) - Error: invalid JsonNode type
2022-07-04 03:01:06,155 ERROR [pool-2-thread-1] index.IndexCollection$LocalIndexerThread (IndexCollection.java:255) - pool-2-thread-1: Unexpected Exception:
java.lang.RuntimeException: Document does not have the required "docid" field!
 at io.anserini.collection.MrTyDiCollection$Document.id(MrTyDiCollection.java:126) ~[anserini-0.14.4-SNAPSHOT.jar:?]
 at io.anserini.index.generator.DefaultLuceneDocumentGenerator.createDocument(DefaultLuceneDocumentGenerator.java:57) ~[anserini-0.14.4-SNAPSHOT.jar:?]
 at io.anserini.index.IndexCollection$LocalIndexerThread.run(IndexCollection.java:202) [anserini-0.14.4-SNAPSHOT.jar:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
 at java.lang.Thread.run(Thread.java:829) [?:?]
2022-07-04 03:01:06,157 ERROR [pool-2-thread-1] index.IndexCollection$LocalIndexerThread (IndexCollection.java:255) - pool-2-thread-1: Unexpected Exception:
java.lang.RuntimeException: Document does not have the required "docid" field!
 at io.anserini.collection.MrTyDiCollection$Document.id(MrTyDiCollection.java:126) ~[anserini-0.14.4-SNAPSHOT.jar:?]
 at io.anserini.index.generator.DefaultLuceneDocumentGenerator.createDocument(DefaultLuceneDocumentGenerator.java:57) ~[anserini-0.14.4-SNAPSHOT.jar:?]
 at io.anserini.index.IndexCollection$LocalIndexerThread.run(IndexCollection.java:202) [anserini-0.14.4-SNAPSHOT.jar:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
 at java.lang.Thread.run(Thread.java:829) [?:?]`

**Comment by crystina-z** [comment]
Hi @xiyanghu, tho I haven't really met this error before, I assume the cause is that the corpus doesn't match the `--collection` specified to pyserini -

if you are using the `{id: .., content: ..}` formatted documents files, this command should reproduce the bm25 index - 
```
python -m pyserini.index.lucene --collection JsonCollection \
  --generator DefaultLuceneDocumentGenerator -threads 16 \
  --input path/to/corpus \
  --index path/to/index \
  --storePositions --storeDocvectors --storeRaw --optimize --language ar
```

and if it's `{docid: .., title: ... , text: ....}` formated documents files (which can be downloaded [here](https://huggingface.co/datasets/castorini/mr-tydi-corpus/tree/main)), this command should reproduce:
```
python -m pyserini.index.lucene --collection MrTyDiCollection \
  --generator DefaultLuceneDocumentGenerator -threads 16 \
  --input path/to/corpus \
  --index path/to/index \
  --storePositions --storeDocvectors --storeRaw --optimize --language ar
```
